@startuml
!include ./C4_templates/C4_Context.puml
!include ./C4_templates/C4_Container.puml
!include ./C4_templates/C4_Component.puml

Person(admin, "Администратор")
Person(tech_pod, "Тех. поддержка")
Person(сlient, "Клиент")
Person(worker, "Тех. специалист")

Person(warm_system, "Система отопления", $sprite="robot")
Person(temp_sensor, "Датчик температуры", $sprite="robot")
System_Boundary(c1, "'Warmhouse'") {
    Container(app_backend, "Backend", "Java", "Управление отоплением дома")
    Container(database, "База данных", "PostgreSQL")
    Container(web, "Web-Клиент", "JS")
    Container(admin_panel, "Админка", "JS")
}

Rel(app_backend, database, "")
Rel(web,app_backend,  "")
Rel(admin_panel, app_backend, "")

Rel(сlient, web, "Управление отоплением. Мониторинг температуры.")
Rel(admin, admin_panel, "Управление заявками на подключение.")
Rel(tech_pod, admin_panel, "Техническая поддержка")
Rel(worker, admin_panel, "Подключение системы отопления в доме")

Rel(app_backend, warm_system, "Включение/выключение отопления")
Rel(app_backend, temp_sensor, "Информация о температуре")
@enduml 
